# Generated by Django 4.2.7 on 2026-03-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Vendas 08h-18h', max_length=80)),
                ('tipo', models.CharField(choices=[('padrao', 'Padrão (08h-18h)'), ('comercial', 'Comercial'), ('12x36', '12x36'), ('noturno', 'Noturno'), ('flexivel', 'Flexível')], default='padrao', max_length=20)),
                ('hora_entrada_planejada', models.TimeField(default='08:00', help_text='Entrada planejada')),
                ('hora_saida_planejada', models.TimeField(default='18:00', help_text='Saída planejada')),
                ('hora_inicio_intervalo', models.TimeField(blank=True, default='12:00', null=True)),
                ('hora_fim_intervalo', models.TimeField(blank=True, default='13:00', null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='marcacao',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rtt.departamento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rtt.jornada'),
        ),
    ]
