# Generated by Django 4.2.29 on 2026-03-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0002_backoffice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
