# Generated by Django 4.2.29 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0003_profile_endereco_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Obrigatório ao marcar saída sem ter registado pausa para almoço.'),
        ),
    ]
