# Generated by Django 4.2.30 on 2026-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0004_marcacao_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
