# Generated by Django 4.2.30 on 2026-05-11 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0005_alter_profile_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('km_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('km_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('veiculo', models.CharField(blank=True, help_text='Matrícula ou identificação do veículo', max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('timestamp_inicial', models.DateTimeField(blank=True, null=True)),
                ('timestamp_final', models.DateTimeField(blank=True, null=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_km', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de KM',
                'verbose_name_plural': 'Registos de KM',
                'ordering': ['-data'],
                'unique_together': {('utilizador', 'data')},
            },
        ),
    ]
