# Generated by Django 4.2.30 on 2026-05-12 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0006_registrokm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrokm',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registo de KM', 'verbose_name_plural': 'Registos de KM'},
        ),
        migrations.AlterUniqueTogether(
            name='registrokm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registrokm',
            name='descricao',
            field=models.CharField(blank=True, help_text='Onde estou / observações', max_length=255),
        ),
        migrations.AddField(
            model_name='registrokm',
            name='km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do KM no momento', max_digits=10),
        ),
        migrations.AddField(
            model_name='registrokm',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrokm',
            name='veiculo',
            field=models.CharField(blank=True, help_text='Matrícula/ID do veículo', max_length=50),
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='km_final',
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='km_inicial',
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='timestamp_final',
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='timestamp_inicial',
        ),
    ]
