# Generated by Django 4.2.30 on 2026-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0007_alter_registrokm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrokm',
            name='km',
            field=models.IntegerField(default=0, help_text='Valor do KM no momento'),
        ),
    ]
