# Generated by Django 4.2.30 on 2026-05-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0008_alter_registrokm_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=100)),
                ('km_inicial', models.IntegerField(default=0, help_text='KM no momento do cadastro no sistema')),
                ('km_atual', models.IntegerField(default=0, help_text='KM atualizado automaticamente')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
            },
        ),
        migrations.RemoveField(
            model_name='registrokm',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='registrokm',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos', to='rtt.viatura'),
        ),
    ]
