# Generated by Django 4.2.30 on 2026-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0009_viatura_remove_registrokm_veiculo_registrokm_viatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrokm',
            name='km_anterior',
            field=models.IntegerField(default=0, help_text='Valor do KM antes deste registo'),
        ),
    ]
