# Generated by Django 4.2.30 on 2026-05-13 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0010_registrokm_km_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rtt.viatura'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
