# Generated by Django 4.2.30 on 2026-05-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0011_profile_viatura_alter_marcacao_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='colaborador_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas_atuais', to=settings.AUTH_USER_MODEL),
        ),
    ]
