# Generated by Django 4.2.30 on 2026-05-17 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0012_viatura_colaborador_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20),
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.DateField(auto_now_add=True)),
                ('km', models.IntegerField(help_text='KM no momento do abastecimento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor gasto (€)', max_digits=8)),
                ('litros', models.DecimalField(blank=True, decimal_places=2, help_text='Litros abastecidos', max_digits=6, null=True)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='comprovativos_abastecimento/')),
                ('comprovativo_texto_ocr', models.TextField(blank=True, help_text='Texto extraído por OCR da fatura/recibo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_admin', models.TextField(blank=True, help_text='Observações da aprovação/rejeição')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='rtt.viatura')),
            ],
            options={
                'verbose_name': 'Abastecimento de Combustível',
                'verbose_name_plural': 'Abastecimentos de Combustível',
                'ordering': ['-timestamp'],
            },
        ),
    ]
