# Generated by Django 4.2.30 on 2026-05-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0013_alter_marcacao_tipo_abastecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrokm',
            name='descricao',
        ),
    ]
