# Generated by Django 4.2.30 on 2026-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtt', '0014_remove_registrokm_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='cartao',
            field=models.CharField(blank=True, help_text='Nº do cartão utilizado', max_length=100, null=True),
        ),
    ]
