# Generated by Django 4.2.30 on 2026-05-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0015_abastecimento_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro (€)'), ('cartao', 'Cartão')], default='dinheiro', max_length=20),
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Identificação do cartão (ex: Galp Frota)', max_length=100)),
                ('numero', models.CharField(help_text='Número completo do cartão', max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('colaborador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_atuais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Combustível',
                'verbose_name_plural': 'Cartões de Combustível',
            },
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='cartao_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='rtt.cartao'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='rtt.cartao'),
        ),
    ]
