# Generated by Django 4.2.30 on 2026-05-18 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rtt', '0016_abastecimento_metodo_pagamento_cartao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaturaHistoricoAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_viaturas', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atribuicoes', to='rtt.viatura')),
            ],
            options={
                'verbose_name': 'Histórico de Atribuição de Viatura',
                'verbose_name_plural': 'Históricos de Atribuições de Viaturas',
                'ordering': ['-data_atribuicao'],
            },
        ),
        migrations.CreateModel(
            name='CartaoHistoricoAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atribuicoes', to='rtt.cartao')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atribuição de Cartão',
                'verbose_name_plural': 'Históricos de Atribuições de Cartões',
                'ordering': ['-data_atribuicao'],
            },
        ),
    ]
